# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "generate"
  - "slack"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "nightmar39/test_repo"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"
  newStep1:
    title: Running docker image
    type: freestyle
    working_directory: '${{CLONE_STEP_NAME}}'
    arguments:
      image: 'quay.io/codefreshplugins/alpine:3.8'
      commands:
        - echo "Hello world"
        - echo "asdasd"

    
